name: CI

on:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Run linter
        run: go vet ./...

      - name: Run formatter
        run: gofmt -l -s -w . 

      - name: Run tests
        run: go test ./... 

      - name: Build
        run: go build ./...
